# Generated by Django 2.0.6 on 2018-07-22 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'count',
            },
        ),
        migrations.CreateModel(
            name='Emoji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'emoji',
            },
        ),
        migrations.AddField(
            model_name='count',
            name='fk_emoji',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Emoji'),
        ),
    ]
